name = "NLSolvers"
uuid = "337daf1e-9722-11e9-073e-8b9effe078ba"
authors = ["Patrick Kofod Mogensen <patrick.mogensen@gmail.com>"]
version = "0.1.0"

[deps]
AIBECS = "ace601d6-714c-11e9-04e5-89b7fad23838"
Atom = "c52e3926-4ff0-5f6e-af25-54175e0327b1"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticOptim = "814864de-89d5-11e8-1c72-cfea42f978d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ArbNumerics", "DoubleFloats", "GeometryTypes", "Printf", "StaticArrays", "Random"]
