name = "NLSolvers"
uuid = "337daf1e-9722-11e9-073e-8b9effe078ba"
version = "0.5.0"
authors = ["Patrick Kofod Mogensen <patrick.mogensen@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.8.14"
ArbNumerics = "1"
DoubleFloats = "1"
ExplicitImports = "1.14.0"
ForwardDiff = "0.9,1"
GenericLinearAlgebra = "0.3"
GeometryTypes = "0.8"
IterativeSolvers = "0.9"
JET = "0.9,0.10"
LinearAlgebra = "1"
LinearMaps = "2, 3"
PositiveFactorizations = "0.2"
Printf = "1"
Random = "1"
SparseArrays = "1"
SparseDiffTools = "1,2"
StaticArrays = "1"
Statistics = "1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "ArbNumerics", "DoubleFloats", "ExplicitImports", "ForwardDiff", "GeometryTypes", "IterativeSolvers", "JET", "LinearMaps", "Printf", "StaticArrays", "SparseDiffTools", "SparseArrays", "Random", "GenericLinearAlgebra"]
